### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by dmgm** [bddean/emacs-ereader#15] opened 2017-07-24 22:37 UTC
I downloaded this book from gutenburg
http://www.gutenberg.org/ebooks/4217
specifically the epub with pictures.

After installing ereader, the book opens but the chapter links on the first 'page' do not work, returning a 'link not found' message.

I opened the same book in iBooks and the links do work.

It's fantastic to be able to open reference books in emacs and search them. thank you.
I've not worked out how to annotate yet either.

**Comment by bddean** [comment] 2017-07-28 00:11
Hello,

I can't reproduce. (You're talking about the CHAPTER 1, CHAPTER 2, ..., CHAPTER 5 links, right?) Which version of emacs are you using? Gui or terminal? Is it happening with other ebooks or just this one?

For annotations, you need to set the ereader-annotations-files variable to associate some orgmode files with your books, and annotations should populate from your notes. There's an example of setting that variable here: https://github.com/bddean/emacs-ereader/issues/10

So that
```
 - [[ebook:/path/to/book.epub::@Chapter 1::$It was a dark and stormy night][link]] What a cheesy opening 
```
Should add an annotation to that position in the book if they're associated, if I remember right. You might need to experiment a little or look at `ereader-load-annotations`. Honestly I didn't find annotations that useful, so they got half-developed with this goofy interface.

Ben

**Comment by dmgm** [comment] 2017-07-28 05:12
I'm using emacs 25.1 gui on macos, installed via nix.
Yes, I'm talking about CHAPTER 1, CHAPTER 2, ..., CHAPTER 5 links.
Yes it happens with other books, but not all other books, Some work.
I'm clicking on the links with the mouse.

I tried opening emacs -nw in a console.
Strangely opening a epub in the console version does not appear to invoke ereader, instead I get a dired view of the epub archive. Not sure why that is.

Thanks for the explanation of annotations.

The error message is "Link target not found".

Links in this book, do work.
https://ebooks.adelaide.edu.au/b/burnett/frances_hodgson/secret-garden/index.html

**Comment by bddean** [comment] 2017-08-10 05:06
Sorry for the very long delay. Should be fixed

**Closed as completed** 2017-08-10 05:05 UTC
